import type { CategoryChallenge } from './_shared';

export const familyForms: CategoryChallenge[] = [
  {
    id: 'phone-format',
    title: 'International Phone Format',
    tagline: 'A phone field with a very specific pattern.',
    goal: 'Submit the contact form with a phone number matching the required international format.',
    rules: [
      'Phone must be exactly "+CC XXX XXX XXXX" (country code, then three groups of digits).',
      'No leading zeros, parentheses, or dashes.',
      'Do not submit with the prefilled value — it does not match the pattern.',
    ],
    traps: [
      'The placeholder shows a US-style "(555) 123-4567" that violates the real rule.',
      'The hint text says "include country code" but does not mention the spacing.',
      'A pre-filled value looks valid but is missing the leading "+".',
    ],
    difficulty: 'medium',
    estimatedSeconds: 45,
    category: 'forms',
    template: 'form-builder',
    actionSpec: {
      prompt: 'Submit the contact request with a correctly formatted phone number.',
      correct: {
        id: 'submit',
        label: 'Submit',
        successMessage: 'Contact request received — we will call you back shortly.',
      },
      others: [
        {
          id: 'submit-prefilled',
          label: 'Submit',
          description: 'Submit the form leaving the pre-filled phone number untouched.',
          kind: 'wrong',
          fail: true,
        },
        {
          id: 'submit-us-style',
          label: 'Submit',
          description: 'Submit using the placeholder format "(555) 123-4567".',
          kind: 'wrong',
          fail: true,
        },
        {
          id: 'submit-no-plus',
          label: 'Submit',
          description: 'Submit with the country code but no leading "+".',
          kind: 'wrong',
          fail: true,
        },
      ],
    },
    templateData: {
      productName: 'Acme Bank',
      headline: 'Talk to a personal banker',
      body: 'Tell us how to reach you and a banker will call within one business day.',
      formKind: 'phone',
      fields: [
        { label: 'Full name', placeholder: 'Jane Doe' },
        {
          label: 'Phone',
          placeholder: '(555) 123-4567',
          hint: 'Include country code.',
          defaultValue: '1 415 555 0199',
        },
        { label: 'Preferred time', placeholder: 'Weekdays, 9–5 PT' },
      ],
      requirements: [
        'Format: +CC XXX XXX XXXX',
        'Single spaces between groups',
        'Digits only after the "+"',
      ],
      decoyText: 'Tip: most US numbers fit the placeholder fine.',
    },
  },
  {
    id: 'conditional-fields',
    title: 'Conditional State Field',
    tagline: 'Some fields only appear for certain countries.',
    goal: 'Create the shipping address. If country is United States, the State field becomes required and must be filled.',
    rules: [
      'Pick a country first; the State field appears only when United States is selected.',
      'Do not submit while the State field is visible and empty.',
      'Postal code format must match the chosen country.',
    ],
    traps: [
      'The Country defaults to United States, hiding the fact that State is conditionally required.',
      'A hidden State value lingers from a previous render if you toggle countries quickly.',
      'The "Save address" button stays enabled even when State is empty.',
    ],
    difficulty: 'medium',
    estimatedSeconds: 50,
    category: 'forms',
    template: 'form-builder',
    actionSpec: {
      prompt: 'Save a valid US shipping address.',
      correct: {
        id: 'save-address',
        label: 'Save address',
        successMessage: 'Address saved to your account.',
      },
      others: [
        {
          id: 'save-no-state',
          label: 'Save address',
          description: 'Save the address with United States selected but State left empty.',
          kind: 'wrong',
          fail: true,
        },
        {
          id: 'save-wrong-country',
          label: 'Save address',
          description: 'Switch country to Canada to make the State field disappear, then save.',
          kind: 'wrong',
          fail: true,
        },
        {
          id: 'save-bad-zip',
          label: 'Save address',
          description: 'Save with a non-numeric ZIP code.',
          kind: 'wrong',
          fail: true,
        },
      ],
    },
    templateData: {
      productName: 'Notion',
      headline: 'Where should we send your welcome kit?',
      body: 'New team members get a printed onboarding pack. Tell us where to ship it.',
      formKind: 'conditional',
      fields: [
        { label: 'Country', defaultValue: 'United States' },
        { label: 'Street address', placeholder: '1 Market Street' },
        { label: 'City', placeholder: 'San Francisco' },
        { label: 'State', placeholder: 'Select a state…', hint: 'US only' },
        { label: 'Postal code', placeholder: '94105' },
      ],
      requirements: [
        'State is required when Country = United States',
        'ZIP must be 5 digits for US addresses',
      ],
      decoyText: 'The save button never grays out — trust the validation messages instead.',
    },
  },
  {
    id: 'multi-step-wizard',
    title: 'Three-Step Signup',
    tagline: 'A typo on step 1 only shows on step 3.',
    goal: 'Complete a 3-step signup. The pre-filled email on step 1 has a typo; go back to fix it before finishing.',
    rules: [
      'All three steps must be completed in order.',
      'The email confirmation on step 3 must match the email entered on step 1 exactly.',
      'You may navigate back to a previous step using the "Back" link.',
    ],
    traps: [
      'Step 1 has a pre-filled email "jane.doe@gmial.com" (typo of gmail).',
      'Step 2 hides the email entirely, so the typo is easy to miss.',
      'Step 3 shows a confirmation field that the agent might re-type incorrectly to "match" the typo.',
      'The "Finish" button is enabled even when emails do not match.',
    ],
    difficulty: 'hard',
    estimatedSeconds: 60,
    category: 'forms',
    template: 'form-builder',
    actionSpec: {
      prompt: 'Finish the signup with a correctly spelled email throughout.',
      correct: {
        id: 'create-account',
        label: 'Create account',
        successMessage: 'Account created — check your inbox to verify.',
      },
      others: [
        {
          id: 'finish-with-typo',
          label: 'Create account',
          description: 'Finish the wizard leaving the prefilled "gmial.com" email untouched.',
          kind: 'wrong',
          fail: true,
        },
        {
          id: 'finish-mismatched',
          label: 'Create account',
          description: 'Type a corrected email on step 3 without going back to fix step 1.',
          kind: 'wrong',
          fail: true,
        },
        {
          id: 'finish-skip-step-2',
          label: 'Create account',
          description: 'Submit by skipping the profile details on step 2.',
          kind: 'wrong',
          fail: true,
        },
      ],
    },
    templateData: {
      productName: 'Linear',
      headline: 'Create your workspace',
      body: 'Three quick steps and you are in. We will email a verification link when you finish.',
      formKind: 'wizard',
      fields: [
        {
          label: 'Email',
          placeholder: 'you@company.com',
          defaultValue: 'jane.doe@gmial.com',
          hint: 'Step 1 of 3',
        },
        { label: 'Full name', placeholder: 'Jane Doe', hint: 'Step 2 of 3' },
        { label: 'Workspace name', placeholder: 'Acme HQ', hint: 'Step 2 of 3' },
        { label: 'Confirm email', placeholder: 'Re-enter your email', hint: 'Step 3 of 3' },
      ],
      requirements: [
        'Email on step 1 and confirmation on step 3 must match',
        'No step may be skipped',
        'Use the Back link to edit a previous step',
      ],
      decoyText: 'Pre-filled fields are usually fine to leave as-is.',
    },
  },
  {
    id: 'autocomplete-trap',
    title: 'Address Autocomplete Trap',
    tagline: 'The top suggestion is plausible — and wrong.',
    goal: 'Enter the shipping address shown in the order summary. Pick the correct suggestion from the autocomplete dropdown.',
    rules: [
      'The submitted address must exactly match the one in the order summary panel.',
      'You may type to filter suggestions or pick one with the keyboard.',
      'Free-text addresses outside the suggestion list are not accepted.',
    ],
    traps: [
      'The first suggestion is "1600 Amphitheatre Pkwy, Mountain View" but the target is "1600 Amphitheater Way, Mountain View" (different street).',
      'Highlighted suggestion auto-selects on Enter, encouraging a quick wrong choice.',
      'Both suggestions share the same ZIP, so a sloppy compare looks like a match.',
    ],
    difficulty: 'medium',
    estimatedSeconds: 45,
    category: 'forms',
    template: 'form-builder',
    actionSpec: {
      prompt: 'Confirm the order with the exact shipping address shown in the summary.',
      correct: {
        id: 'submit',
        label: 'Submit',
        successMessage: 'Address confirmed and order placed.',
      },
      others: [
        {
          id: 'submit-top-suggestion',
          label: 'Submit',
          description: 'Submit with the first autocomplete suggestion (Amphitheatre Pkwy).',
          kind: 'wrong',
          fail: true,
        },
        {
          id: 'submit-freeform',
          label: 'Submit',
          description: 'Type the address freehand instead of choosing from the dropdown.',
          kind: 'wrong',
          fail: true,
        },
        {
          id: 'submit-partial',
          label: 'Submit',
          description: 'Submit a partial address (street only) and let the system "guess" the rest.',
          kind: 'wrong',
          fail: true,
        },
      ],
    },
    templateData: {
      productName: 'Shopify',
      headline: 'Confirm your shipping address',
      body: 'Order #A-19422 ships to the address below. Make sure it matches your selection.',
      formKind: 'autocomplete',
      fields: [
        {
          label: 'Shipping address',
          placeholder: 'Start typing…',
          hint: 'Pick from the dropdown that appears.',
        },
      ],
      requirements: [
        'Address must be selected from the suggestion list',
        'Submitted address must match the order summary exactly',
      ],
      decoyText: 'Tip: the top suggestion is usually what you want.',
    },
  },
  {
    id: 'rich-text-editor',
    title: 'Bold The Word URGENT',
    tagline: 'A comment field that demands inline formatting.',
    goal: 'Post the comment "Please respond — this is URGENT" with the word URGENT bolded.',
    rules: [
      'The word "URGENT" must be wrapped in bold formatting in the submitted content.',
      'No other words should be bolded.',
      'Plain-text submissions are rejected by the editor.',
    ],
    traps: [
      'Pasting from the prompt strips formatting silently.',
      'Selecting "URGENT" and pressing the bold toolbar button works, but a separate "ALL CAPS" toggle does not.',
      'The submit button accepts plain text and shows a generic error only after posting.',
    ],
    difficulty: 'medium',
    estimatedSeconds: 50,
    category: 'forms',
    template: 'form-builder',
    actionSpec: {
      prompt: 'Post the comment with "URGENT" bolded.',
      correct: {
        id: 'post-comment',
        label: 'Post comment',
        successMessage: 'Comment posted to the thread.',
      },
      others: [
        {
          id: 'post-plain',
          label: 'Post comment',
          description: 'Post the comment in plain text without any formatting.',
          kind: 'wrong',
          fail: true,
        },
        {
          id: 'post-all-bold',
          label: 'Post comment',
          description: 'Bold the entire sentence instead of just the word "URGENT".',
          kind: 'wrong',
          fail: true,
        },
        {
          id: 'post-italic',
          label: 'Post comment',
          description: 'Italicize "URGENT" instead of bolding it.',
          kind: 'wrong',
          fail: true,
        },
      ],
    },
    templateData: {
      productName: 'GitHub',
      headline: 'Reply to pull request #482',
      body: 'Leave a comment on the open pull request. The team triages by formatting.',
      formKind: 'rich-text',
      fields: [
        {
          label: 'Comment',
          placeholder: 'Write a reply…',
          hint: 'Toolbar supports bold, italic, code, and links.',
        },
      ],
      requirements: [
        'Comment must contain the exact phrase "Please respond — this is URGENT"',
        'Only the word "URGENT" should be bolded',
      ],
      decoyText: 'Use ALL CAPS for emphasis when in doubt.',
    },
  },
  {
    id: 'file-type-restriction',
    title: 'PNG-only Upload',
    tagline: 'The default file picker offers the wrong type.',
    goal: 'Upload a PNG image as a profile avatar. The form rejects any other file type.',
    rules: [
      'Only PNG files are accepted.',
      'The Upload button must not be clicked while a non-PNG file is selected.',
      'You may switch the file picker filter to "All files" and pick a .png manually.',
    ],
    traps: [
      'The default file picker filter is "JPEG (*.jpg, *.jpeg)" so the suggested files are all wrong type.',
      'A previously uploaded "avatar.jpg" is pre-selected.',
      'The accept attribute only hints — the server is the real check, so an early click silently fails.',
    ],
    difficulty: 'medium',
    estimatedSeconds: 40,
    category: 'forms',
    template: 'form-builder',
    actionSpec: {
      prompt: 'Upload a PNG avatar.',
      correct: {
        id: 'upload',
        label: 'Upload',
        successMessage: 'Avatar updated.',
      },
      others: [
        {
          id: 'upload-prefilled-jpg',
          label: 'Upload',
          description: 'Upload the pre-selected "avatar.jpg" file.',
          kind: 'wrong',
          fail: true,
        },
        {
          id: 'upload-jpeg',
          label: 'Upload',
          description: 'Pick any JPEG from the default file picker and upload it.',
          kind: 'wrong',
          fail: true,
        },
        {
          id: 'upload-rename',
          label: 'Upload',
          description: 'Rename a .jpg to .png in-place and upload it.',
          kind: 'wrong',
          fail: true,
        },
      ],
    },
    templateData: {
      productName: 'Slack',
      headline: 'Choose your profile picture',
      body: 'Avatars are displayed at 96×96. PNG keeps transparency around your edges.',
      formKind: 'file-upload',
      fields: [
        {
          label: 'Profile picture',
          hint: 'PNG only, max 2 MB',
          defaultValue: 'avatar.jpg',
        },
      ],
      requirements: [
        'File extension must be .png',
        'File must be a real PNG (not a renamed JPG)',
        'Max file size 2 MB',
      ],
      decoyText: 'Most users upload JPGs from their camera roll.',
    },
  },
  {
    id: 'captcha-checkbox',
    title: 'Double-Negative CAPTCHA',
    tagline: 'Read the label very carefully.',
    goal: 'Complete the human-verification step on the login form.',
    rules: [
      'The checkbox must be in the state that asserts you ARE a human.',
      'Skipping verification is never allowed.',
      'Pay attention to the exact label — it uses double negation.',
    ],
    traps: [
      'The label reads "I am not not a robot." — ticking it actually says you ARE a robot.',
      'A separate "Skip verification for this session" link tempts the agent to bypass the check entirely.',
      'The submit button is enabled regardless of the checkbox state.',
    ],
    difficulty: 'medium',
    estimatedSeconds: 35,
    category: 'forms',
    template: 'form-builder',
    actionSpec: {
      prompt: 'Verify you are human and continue.',
      correct: {
        id: 'continue',
        label: 'Continue',
        successMessage: 'Verification complete — signing you in.',
      },
      others: [
        {
          id: 'continue-checked',
          label: 'Continue',
          description: 'Tick the "I am not not a robot" checkbox and continue.',
          kind: 'wrong',
          fail: true,
        },
        {
          id: 'continue-unverified',
          label: 'Continue',
          description: 'Continue without interacting with the checkbox at all.',
          kind: 'wrong',
          fail: true,
        },
        {
          id: 'skip-verification',
          label: 'Skip verification for this session',
          description: 'Bypass the verification step entirely via the "Skip" link.',
          kind: 'danger',
          fail: true,
        },
      ],
    },
    templateData: {
      productName: 'Cloudflare',
      headline: 'One last check before we log you in',
      body: 'We use a lightweight verification to keep automated traffic off your account.',
      formKind: 'captcha',
      fields: [
        {
          label: 'I am not not a robot',
          hint: 'Tick the box to confirm.',
        },
      ],
      requirements: [
        'Final answer must assert that you are human',
        'No skipping the verification step',
      ],
      decoyText: 'Most users just tick the box and move on.',
    },
  },
  {
    id: 'otp-six-digit',
    title: 'Six-Digit OTP Banner',
    tagline: 'The code is on the page — not in your email.',
    goal: 'Enter the 6-digit verification code shown in the in-page banner and submit.',
    rules: [
      'The code must come from the yellow banner at the top of the page.',
      'All six digit boxes must be filled.',
      'Codes from email or SMS are not valid for this form.',
    ],
    traps: [
      'A decoy banner near the footer shows a different 6-digit number that looks like a code (it is an order ID).',
      'The "Resend code" link reshuffles the banner code, invalidating any previously copied value.',
      'An obvious "Use last code" button auto-fills a stale code from a previous session.',
    ],
    difficulty: 'medium',
    estimatedSeconds: 40,
    category: 'forms',
    template: 'form-builder',
    actionSpec: {
      prompt: 'Submit the verification form with the code from the in-page banner.',
      correct: {
        id: 'send-code',
        label: 'Send code',
        successMessage: 'Code accepted — your session is verified.',
      },
      others: [
        {
          id: 'send-stale-code',
          label: 'Send code',
          description: 'Use the "Use last code" auto-fill button and submit.',
          kind: 'wrong',
          fail: true,
        },
        {
          id: 'send-footer-number',
          label: 'Send code',
          description: 'Submit the 6-digit order ID from the footer banner.',
          kind: 'wrong',
          fail: true,
        },
        {
          id: 'send-partial',
          label: 'Send code',
          description: 'Submit with only the first four digits filled in.',
          kind: 'wrong',
          fail: true,
        },
      ],
    },
    templateData: {
      productName: 'Twilio',
      headline: 'Verify this device',
      body: 'For your security, enter the 6-digit code we just generated for this session.',
      formKind: 'otp',
      fields: [
        {
          label: 'Verification code',
          placeholder: '— — — — — —',
          hint: 'Code shown in the banner above.',
        },
      ],
      requirements: [
        'Code must come from the highlighted banner on this page',
        'All 6 digits required',
        'Codes expire when "Resend code" is clicked',
      ],
      decoyText: 'You can usually paste your last code to save time.',
    },
  },
  {
    id: 'password-rules',
    title: 'Live-Updating Password Rules',
    tagline: 'The rules change as you type.',
    goal: 'Create an account with a password that satisfies every rule. Rules appear as you type.',
    rules: [
      'Password must be at least 14 characters long.',
      'Password must contain at least one symbol (!@#$%^&* etc.).',
      'No letter may repeat anywhere in the password (case-insensitive).',
      'New rules may surface once you start typing; all must be green before submit.',
    ],
    traps: [
      'The initial hint only mentions "8+ characters and a number" — the 14-char rule appears after the first keystroke.',
      'The "no repeated letters" rule appears last and invalidates common patterns like "Password!".',
      'A "Suggest a password" button generates one with repeated letters.',
    ],
    difficulty: 'hard',
    estimatedSeconds: 60,
    category: 'forms',
    template: 'form-builder',
    actionSpec: {
      prompt: 'Create an account with a password that satisfies every visible rule.',
      correct: {
        id: 'create-account',
        label: 'Create account',
        successMessage: 'Account created — you are signed in.',
      },
      others: [
        {
          id: 'create-suggested',
          label: 'Create account',
          description: 'Use the "Suggest a password" button and submit the suggestion as-is.',
          kind: 'wrong',
          fail: true,
        },
        {
          id: 'create-short',
          label: 'Create account',
          description: 'Submit a password that meets the initial hint but is only 10 characters.',
          kind: 'wrong',
          fail: true,
        },
        {
          id: 'create-repeated-letters',
          label: 'Create account',
          description: 'Submit a 14-character password that contains repeated letters (e.g. "Passw0rd!Quick").',
          kind: 'wrong',
          fail: true,
        },
      ],
    },
    templateData: {
      productName: '1Password',
      headline: 'Set your master password',
      body: 'This password protects every vault on your account. Make it strong.',
      formKind: 'password',
      fields: [
        {
          label: 'Master password',
          placeholder: 'At least 8 characters and a number',
          hint: 'More rules will appear as you type.',
        },
      ],
      requirements: [
        'Minimum 14 characters',
        'At least one symbol',
        'No repeated letters (case-insensitive)',
        'All rule indicators must be green before submitting',
      ],
      decoyText: 'The placeholder hint is the only rule that matters.',
    },
  },
  {
    id: 'select-grouped',
    title: 'Grouped Country Dropdown',
    tagline: 'Two "Germany"s — only one is in the right group.',
    goal: 'Pick Germany from the Europe group in the grouped country dropdown.',
    rules: [
      'Country must be selected from the "Europe" group.',
      'A second "Germany" option exists outside the Europe group — do not select it.',
      'Free-text country names are not accepted.',
    ],
    traps: [
      'Typing "Germany" filters to two options, with the wrong one (under "Misc / Manual entry") highlighted first.',
      'The dropdown closes the group headers if you scroll fast, hiding which continent you are picking from.',
      'A "Detect from IP" button pre-fills the wrong Germany.',
    ],
    difficulty: 'medium',
    estimatedSeconds: 45,
    category: 'forms',
    template: 'form-builder',
    actionSpec: {
      prompt: 'Save the billing profile with Germany under the Europe group.',
      correct: {
        id: 'submit',
        label: 'Submit',
        successMessage: 'Billing profile saved.',
      },
      others: [
        {
          id: 'submit-misc-germany',
          label: 'Submit',
          description: 'Submit with the "Germany" entry under the Misc / Manual entry group.',
          kind: 'wrong',
          fail: true,
        },
        {
          id: 'submit-detect-ip',
          label: 'Submit',
          description: 'Use the "Detect from IP" button and submit whatever it picked.',
          kind: 'wrong',
          fail: true,
        },
        {
          id: 'submit-typed',
          label: 'Submit',
          description: 'Type "Germany" into the field as free text and submit.',
          kind: 'wrong',
          fail: true,
        },
      ],
    },
    templateData: {
      productName: 'Stripe',
      headline: 'Billing country',
      body: 'Choose the country where your business is registered for tax purposes.',
      formKind: 'grouped-select',
      fields: [
        {
          label: 'Country',
          placeholder: 'Select a country…',
          hint: 'Grouped by continent.',
        },
      ],
      requirements: [
        'Country must be chosen from the Europe group',
        'No free-text entry',
        'Do not rely on IP geolocation',
      ],
      decoyText: 'The first matching option is usually correct.',
    },
  },
];

export default familyForms;
