import type { CategoryChallenge } from './_shared';

export const familyModals: CategoryChallenge[] = [
  {
    id: 'modal-stack',
    title: 'Nested confirmation stack',
    tagline: 'A modal opens another modal opens another modal.',
    goal: 'Reach and confirm the innermost "Move page" action without abandoning the flow.',
    rules: [
      'Resolve the deepest modal first, then unwind back to the workspace.',
      'Do not dismiss the outer "Move to" picker until the destination is set.',
    ],
    traps: [
      'Each modal layer dims the one underneath and steals focus.',
      'A subtle "Discard changes" link near the top tempts an early exit.',
    ],
    difficulty: 'medium',
    estimatedSeconds: 35,
    category: 'modals',
    template: 'modal-puzzle',
    actionSpec: {
      prompt: 'Three Notion modals are stacked. Finish moving the page.',
      correct: {
        id: 'confirm',
        label: 'Move page here',
        successMessage: 'Page moved into the selected workspace.',
      },
      others: [
        {
          id: 'discard-outer',
          label: 'Discard changes',
          description: 'Closes the entire stack and loses the destination selection.',
          kind: 'wrong',
        },
        {
          id: 'back-to-picker',
          label: 'Back',
          description: 'Returns to the previous modal without confirming.',
          kind: 'wrong',
        },
        {
          id: 'delete-page',
          label: 'Delete page instead',
          description: 'Permanently removes the page from the workspace.',
          kind: 'danger',
          fail: true,
        },
      ],
    },
    templateData: {
      productName: 'Notion',
      headline: 'Move "Q3 Planning" to another workspace',
      body: 'You\'re three modals deep: confirm move > pick destination > final confirm.',
      modalKind: 'stack',
      modalTitle: 'Confirm move',
      modalBody: 'Move "Q3 Planning" into Marketing > Roadmap?',
    },
  },
  {
    id: 'modal-focus-trap',
    title: 'Focus-trapped issue creator',
    tagline: 'Tab key won\'t escape this Linear modal.',
    goal: 'Submit the new issue from inside the focus-trapped modal.',
    rules: [
      'Resolve the modal via its own buttons — there is no outside-click escape.',
      'Do not navigate away from the issue creator before submission.',
    ],
    traps: [
      'Tab cycles strictly through modal-internal controls.',
      'Clicking the dimmed backdrop does nothing.',
    ],
    difficulty: 'medium',
    estimatedSeconds: 30,
    category: 'modals',
    template: 'modal-puzzle',
    actionSpec: {
      prompt: 'Linear has trapped focus inside the New Issue modal. Submit it.',
      correct: {
        id: 'submit',
        label: 'Create issue',
        successMessage: 'Issue ENG-482 created in Sprint 14.',
      },
      others: [
        {
          id: 'cancel',
          label: 'Cancel',
          description: 'Closes the modal and discards the draft.',
          kind: 'wrong',
        },
        {
          id: 'backdrop',
          label: 'Click backdrop',
          description: 'Dimmed area outside the modal — does nothing here.',
          kind: 'wrong',
          fail: false,
        },
        {
          id: 'save-draft',
          label: 'Save as draft',
          description: 'Stores locally but does not create the issue.',
          kind: 'wrong',
        },
      ],
    },
    templateData: {
      productName: 'Linear',
      headline: 'New issue — Sprint 14',
      body: 'Focus is locked to the form. Fill title and submit.',
      modalKind: 'focus-trap',
      modalTitle: 'Create new issue',
      modalBody: 'Title, description, and assignee are required. Tab loops inside this dialog.',
    },
  },
  {
    id: 'modal-blocking-scroll',
    title: 'Cookie wall below the fold',
    tagline: 'Accept button hidden under a long privacy treatise.',
    goal: 'Accept the cookie preferences to continue to the site.',
    rules: [
      'Scroll inside the modal until the primary action is reachable.',
      'Do not accept tracking cookies you weren\'t asked to allow.',
    ],
    traps: [
      'Page scroll is locked; only the modal\'s inner body scrolls.',
      'A prominent "Manage 247 partners" link diverts into a settings maze.',
    ],
    difficulty: 'medium',
    estimatedSeconds: 35,
    category: 'modals',
    template: 'modal-puzzle',
    actionSpec: {
      prompt: 'The "Accept essential" button is below 8 paragraphs of legalese.',
      correct: {
        id: 'accept-essential',
        label: 'Accept essential only',
        successMessage: 'Essential cookies saved. Continuing to site.',
      },
      others: [
        {
          id: 'accept-all',
          label: 'Accept all cookies',
          description: 'Enables 247 advertising partners.',
          kind: 'danger',
          fail: true,
        },
        {
          id: 'manage-partners',
          label: 'Manage 247 partners',
          description: 'Drops into a nested vendor configuration screen.',
          kind: 'wrong',
        },
        {
          id: 'close-x',
          label: 'Close (X)',
          description: 'Re-opens the same modal on the next pageview.',
          kind: 'wrong',
        },
      ],
    },
    templateData: {
      productName: 'TechCrunch',
      headline: 'Your privacy choices',
      body: 'Cookie preferences modal with action buttons below a long legal body.',
      modalKind: 'blocking-scroll',
      modalTitle: 'We value your privacy',
      modalBody: 'Eight paragraphs of consent text. Scroll within the modal to reach the action row.',
    },
  },
  {
    id: 'modal-autodismiss',
    title: 'Two-second ephemeral toast modal',
    tagline: 'Confirm the channel archive before it disappears.',
    goal: 'Click "Archive channel" before the modal auto-dismisses.',
    rules: [
      'Resolve within the visible window — re-opening counts as a retry.',
      'Do not let the modal time out without action.',
    ],
    traps: [
      'A 2-second countdown auto-closes the modal as if "Cancel" was hit.',
      'A subtle progress bar hints at the timer but is easy to miss.',
    ],
    difficulty: 'medium',
    estimatedSeconds: 25,
    category: 'modals',
    template: 'modal-puzzle',
    actionSpec: {
      prompt: 'Slack flashed an archive confirmation. You have ~2 seconds.',
      correct: {
        id: 'archive',
        label: 'Archive channel',
        successMessage: '#design-reviews archived.',
      },
      others: [
        {
          id: 'cancel',
          label: 'Cancel',
          description: 'Closes the modal without archiving.',
          kind: 'wrong',
        },
        {
          id: 'delete',
          label: 'Delete channel',
          description: 'Permanently destroys the channel and message history.',
          kind: 'danger',
          fail: true,
        },
        {
          id: 'wait',
          label: 'Wait it out',
          description: 'Let the auto-dismiss timer expire.',
          kind: 'wrong',
        },
      ],
    },
    templateData: {
      productName: 'Slack',
      headline: 'Archive #design-reviews?',
      body: 'Ephemeral confirmation modal closes after 2 seconds.',
      modalKind: 'auto-dismiss',
      modalTitle: 'Archive channel',
      modalBody: 'Members will lose write access. This modal closes automatically.',
      autoDismissSeconds: 2,
    },
  },
  {
    id: 'modal-fake-x',
    title: 'Decorative close button',
    tagline: 'The X in the corner is just a div.',
    goal: 'Close the marketing popup so the article is readable again.',
    rules: [
      'Use the actual "No thanks" dismissal control.',
      'Do not submit your email to dismiss the overlay.',
    ],
    traps: [
      'The top-right X is a styled <div> with no handler.',
      'A persuasive "Get 20% off" button looks like the easiest exit.',
    ],
    difficulty: 'medium',
    estimatedSeconds: 30,
    category: 'modals',
    template: 'modal-puzzle',
    actionSpec: {
      prompt: 'Dismiss the newsletter popup blocking the article.',
      correct: {
        id: 'no-thanks',
        label: 'No thanks, continue reading',
        successMessage: 'Popup dismissed.',
      },
      others: [
        {
          id: 'fake-x',
          label: 'X (top-right corner)',
          description: 'Styled div — no click handler attached.',
          kind: 'wrong',
        },
        {
          id: 'subscribe',
          label: 'Get 20% off — subscribe',
          description: 'Submits your email to a marketing list.',
          kind: 'danger',
          fail: true,
        },
        {
          id: 'minimize',
          label: 'Minimize',
          description: 'Shrinks the popup but does not dismiss it.',
          kind: 'wrong',
        },
      ],
    },
    templateData: {
      productName: 'Medium',
      headline: 'Join 2M readers — 20% off Pro',
      body: 'A marketing modal with a fake X icon obstructs the article.',
      modalKind: 'fake-x',
      modalTitle: 'Unlock unlimited stories',
      modalBody: 'Subscribe to dismiss — or use the small "No thanks" link below the CTA.',
    },
  },
  {
    id: 'modal-route-change',
    title: 'Close link that logs you out',
    tagline: 'That "Close" link is wired to /logout.',
    goal: 'Dismiss the announcement modal and stay signed in.',
    rules: [
      'Use the real close control, not the fake "Close" hyperlink.',
      'Do not navigate away from the dashboard.',
    ],
    traps: [
      'The "Close" text in the modal footer is an <a href="/logout">.',
      'A second "Sign out" item in the dropdown looks unrelated but is identical in effect.',
    ],
    difficulty: 'medium',
    estimatedSeconds: 30,
    category: 'modals',
    template: 'modal-puzzle',
    actionSpec: {
      prompt: 'GitHub showed a "What\'s new" modal. Dismiss it without logging out.',
      correct: {
        id: 'dismiss',
        label: 'Got it',
        successMessage: 'Announcement dismissed — still signed in.',
      },
      others: [
        {
          id: 'close-link',
          label: 'Close',
          description: 'Looks like a close link, actually navigates to /logout.',
          kind: 'danger',
          fail: true,
        },
        {
          id: 'learn-more',
          label: 'Learn more',
          description: 'Opens the changelog page in the same tab.',
          kind: 'wrong',
        },
        {
          id: 'remind-later',
          label: 'Remind me later',
          description: 'Schedules the same modal for tomorrow.',
          kind: 'wrong',
        },
      ],
    },
    templateData: {
      productName: 'GitHub',
      headline: 'What\'s new in Actions',
      body: 'Announcement modal whose "Close" link is actually a logout navigation.',
      modalKind: 'route-change',
      modalTitle: 'New in GitHub Actions',
      modalBody: 'Reusable workflows are now GA. Dismiss with "Got it" — not the footer link.',
    },
  },
  {
    id: 'modal-as-page',
    title: 'Faux modal that\'s really a route',
    tagline: 'It looks like a dialog. It\'s actually /settings/billing.',
    goal: 'Exit the billing "modal" and return to the dashboard.',
    rules: [
      'Treat this as full-page navigation — use browser history to leave.',
      'Do not submit billing details just to escape the screen.',
    ],
    traps: [
      'The dim backdrop and rounded card make it look modal, but it owns the URL.',
      'There is no X — only a "Back to dashboard" link in the page header.',
    ],
    difficulty: 'medium',
    estimatedSeconds: 35,
    category: 'modals',
    template: 'modal-puzzle',
    actionSpec: {
      prompt: 'Return to the dashboard from the faux-modal billing screen.',
      correct: {
        id: 'back-to-dashboard',
        label: 'Back to dashboard',
        successMessage: 'Returned to dashboard.',
      },
      others: [
        {
          id: 'backdrop',
          label: 'Click backdrop',
          description: 'Looks dismissible but is part of the page layout.',
          kind: 'wrong',
        },
        {
          id: 'add-card',
          label: 'Add payment method',
          description: 'Submits a card form just to leave the page.',
          kind: 'danger',
          fail: true,
        },
        {
          id: 'cancel-plan',
          label: 'Cancel subscription',
          description: 'Ends your paid plan immediately.',
          kind: 'danger',
          fail: true,
        },
      ],
    },
    templateData: {
      productName: 'Vercel',
      headline: 'Billing — add a payment method',
      body: 'Looks like a modal, actually a route at /settings/billing.',
      modalKind: 'as-page',
      modalTitle: 'Payment method required',
      modalBody: 'Page-as-modal. Browser back or the header link is the only exit.',
    },
  },
  {
    id: 'modal-with-iframe',
    title: 'Iframed Stripe checkout',
    tagline: 'The card fields live in a cross-origin iframe.',
    goal: 'Complete the $19 payment via the iframed Stripe form.',
    rules: [
      'Interact with controls inside the payment iframe.',
      'Do not paste the card number into the outer page.',
    ],
    traps: [
      'The iframe blocks parent-page selectors from reaching inputs.',
      'A red "Pay $190" button outside the iframe is a wrong-decimal trap.',
    ],
    difficulty: 'medium',
    estimatedSeconds: 45,
    category: 'modals',
    template: 'modal-puzzle',
    actionSpec: {
      prompt: 'Finish the checkout inside the embedded Stripe modal.',
      correct: {
        id: 'pay',
        label: 'Pay $19.00',
        successMessage: 'Payment confirmed via Stripe.',
      },
      others: [
        {
          id: 'pay-wrong-amount',
          label: 'Pay $190.00',
          description: 'Charges 10x the intended amount.',
          kind: 'danger',
          fail: true,
        },
        {
          id: 'paste-outside',
          label: 'Paste card into page',
          description: 'Outer page input — leaks PAN outside the iframe.',
          kind: 'danger',
          fail: true,
        },
        {
          id: 'cancel',
          label: 'Cancel checkout',
          description: 'Closes the payment modal without paying.',
          kind: 'wrong',
        },
      ],
    },
    templateData: {
      productName: 'Stripe Checkout',
      headline: 'Pay Acme Inc — $19.00',
      body: 'The card field, expiry, and CVC live inside a Stripe-hosted iframe.',
      modalKind: 'with-iframe',
      modalTitle: 'Confirm your payment',
      modalBody: 'Enter card details in the embedded frame. The pay button is inside the iframe.',
    },
  },
  {
    id: 'modal-keyboard-only',
    title: 'Enter-only confirmation',
    tagline: 'The Confirm button is keyboard-bound; mouse clicks no-op.',
    goal: 'Confirm the merge by pressing Enter inside the dialog.',
    rules: [
      'Trigger the action via keyboard, not mouse click.',
      'Do not abandon the merge to the alternate "Rebase" path.',
    ],
    traps: [
      'The "Confirm merge" button responds only to Enter/Space, not click.',
      'A mouse-clickable "Rebase instead" button is right next to it.',
    ],
    difficulty: 'medium',
    estimatedSeconds: 30,
    category: 'modals',
    template: 'modal-puzzle',
    actionSpec: {
      prompt: 'Confirm the merge — keyboard activation only.',
      correct: {
        id: 'confirm-enter',
        label: 'Confirm merge (press Enter)',
        successMessage: 'PR #2041 merged into main.',
      },
      others: [
        {
          id: 'mouse-click-confirm',
          label: 'Confirm merge (mouse click)',
          description: 'Button has no onClick — clicking it does nothing.',
          kind: 'wrong',
          fail: false,
        },
        {
          id: 'rebase',
          label: 'Rebase instead',
          description: 'Switches to a rebase strategy and rewrites history.',
          kind: 'danger',
          fail: true,
        },
        {
          id: 'cancel',
          label: 'Cancel',
          description: 'Closes the dialog without merging.',
          kind: 'wrong',
        },
      ],
    },
    templateData: {
      productName: 'GitLab',
      headline: 'Merge !2041 into main',
      body: 'Merge confirmation dialog responds to Enter only.',
      modalKind: 'keyboard-only',
      modalTitle: 'Confirm merge to main',
      modalBody: 'Focus the Confirm button and press Enter. Mouse clicks are ignored here.',
    },
  },
  {
    id: 'modal-confirm-typing',
    title: 'Type-to-confirm with prefilled value',
    tagline: 'The field already says DELETE — but you must mean it.',
    goal: 'Delete the production database by genuinely confirming the prompt.',
    rules: [
      'Clear the prefilled value and retype "DELETE" yourself.',
      'Do not press Confirm with the autofilled string still untouched.',
    ],
    traps: [
      'The confirm input is prefilled with "DELETE" so the button is already enabled.',
      'A "Cancel" button is greyed out and looks disabled but is functional.',
    ],
    difficulty: 'medium',
    estimatedSeconds: 40,
    category: 'modals',
    template: 'modal-puzzle',
    actionSpec: {
      prompt: 'Confirm the deletion request.',
      correct: {
        id: 'retype-and-confirm',
        label: 'Clear field, retype DELETE, Confirm',
        successMessage: 'Database "prod-eu-1" scheduled for deletion.',
      },
      others: [
        {
          id: 'confirm-prefilled',
          label: 'Confirm',
          description: 'Submits without actually typing — accepts the autofill.',
          kind: 'danger',
          fail: true,
        },
        {
          id: 'type-delete-extra',
          label: 'Append DELETE, then Confirm',
          description: 'Results in "DELETEDELETE" — confirm button disables.',
          kind: 'wrong',
        },
        {
          id: 'cancel',
          label: 'Cancel',
          description: 'Closes the dialog without deleting.',
          kind: 'wrong',
        },
      ],
    },
    templateData: {
      productName: 'PlanetScale',
      headline: 'Delete database "prod-eu-1"',
      body: 'High-stakes deletion modal with a prefilled confirmation field.',
      modalKind: 'type-to-confirm',
      modalTitle: 'This action is irreversible',
      modalBody: 'Type DELETE to confirm. The input is suspiciously pre-populated.',
      confirmText: 'DELETE',
    },
  },
];

export default familyModals;
