import type { CategoryChallenge } from './_shared';

export const familyNavigation: CategoryChallenge[] = [
  {
    id: 'breadcrumb-trap',
    title: 'Breadcrumb Trap',
    tagline: 'The breadcrumb lies about where it leads.',
    goal: 'Return to the admin dashboard from the user detail view.',
    rules: [
      'Use only the on-page navigation controls',
      'Do not sign out of the admin console',
    ],
    traps: [
      'The "Home" breadcrumb link is wired to /logout',
      'The intermediate "Users" crumb is the only safe path back',
    ],
    difficulty: 'medium',
    estimatedSeconds: 35,
    category: 'navigation',
    template: 'navigation-puzzle',
    actionSpec: {
      prompt: 'Get back to the admin dashboard without logging out.',
      correct: {
        id: 'click-users-crumb',
        label: 'Click "Users" in the breadcrumb',
        successMessage: 'Navigated up one level safely.',
      },
      others: [
        {
          id: 'click-home-crumb',
          label: 'Click "Home" in the breadcrumb',
          description: 'Top-most crumb labeled Home',
          kind: 'danger',
        },
        {
          id: 'click-sidebar-billing',
          label: 'Open Billing in the sidebar',
          description: 'Unrelated sidebar destination',
          kind: 'wrong',
        },
        {
          id: 'click-help-widget',
          label: 'Open the floating help widget',
          description: 'Opens a chat overlay',
          kind: 'wrong',
        },
      ],
    },
    templateData: {
      productName: 'Northwind Admin Console',
      headline: 'User detail: ada.lovelace@northwind.io',
      body: 'You are three levels deep in the admin tree. The breadcrumb at the top promises a fast trip home — but one of the links is mis-wired to the logout endpoint.',
      navKind: 'breadcrumb',
      breadcrumb: ['Home', 'Users', 'ada.lovelace@northwind.io'],
    },
  },
  {
    id: 'hash-routing',
    title: 'Hash Routing',
    tagline: 'A long settings page hides billing behind an anchor.',
    goal: 'Jump to the Billing section of the settings page.',
    rules: [
      'Stay on the current settings route',
      'Do not reload the page',
    ],
    traps: [
      'The sidebar "Billing" entry routes to a different product surface',
      'Only the in-page anchor #billing scrolls to the right section',
    ],
    difficulty: 'medium',
    estimatedSeconds: 30,
    category: 'navigation',
    template: 'navigation-puzzle',
    actionSpec: {
      prompt: 'Open the Billing section on this settings page.',
      correct: {
        id: 'click-anchor-billing',
        label: 'Click the "#billing" anchor in the page TOC',
        successMessage: 'Scrolled to the Billing section via hash route.',
      },
      others: [
        {
          id: 'click-sidebar-billing',
          label: 'Open Billing from the global sidebar',
          description: 'Leaves the settings page entirely',
          kind: 'wrong',
        },
        {
          id: 'click-anchor-profile',
          label: 'Click the "#profile" anchor',
          description: 'Wrong section',
          kind: 'wrong',
        },
        {
          id: 'click-upgrade-banner',
          label: 'Click the "Upgrade plan" banner',
          description: 'Marketing CTA at the top',
          kind: 'wrong',
        },
      ],
    },
    templateData: {
      productName: 'Acme Cloud Console',
      headline: 'Account Settings',
      body: 'This is a 4,000-line settings page with a sticky table of contents on the left. The TOC uses hash anchors, but the global sidebar has a same-named "Billing" entry that routes you out of settings.',
      navKind: 'hash',
      tabs: [
        { label: '#profile' },
        { label: '#notifications' },
        { label: '#billing' },
        { label: '#api-keys' },
        { label: '#danger-zone' },
      ],
    },
  },
  {
    id: 'tab-mismatch',
    title: 'Tab Mismatch',
    tagline: 'The "Settings" tab does not contain settings.',
    goal: 'Open the team members list.',
    rules: [
      'Use the tab bar at the top of the workspace',
      'Do not invite a new member',
    ],
    traps: [
      'The "Members" tab shows billing receipts',
      'The "Settings" tab actually renders the members list',
    ],
    difficulty: 'medium',
    estimatedSeconds: 35,
    category: 'navigation',
    template: 'navigation-puzzle',
    actionSpec: {
      prompt: 'Show the list of team members in this workspace.',
      correct: {
        id: 'click-settings-tab',
        label: 'Click the "Settings" tab',
        successMessage: 'Members list rendered (labels are swapped).',
      },
      others: [
        {
          id: 'click-members-tab',
          label: 'Click the "Members" tab',
          description: 'Tab labeled Members',
          kind: 'wrong',
        },
        {
          id: 'click-overview-tab',
          label: 'Click the "Overview" tab',
          description: 'Default landing tab',
          kind: 'wrong',
        },
        {
          id: 'click-invite-button',
          label: 'Click "Invite member"',
          description: 'CTA in the header',
          kind: 'wrong',
        },
      ],
    },
    templateData: {
      productName: 'Linear-style Workspace',
      headline: 'Workspace: paper-airplane',
      body: 'The workspace has four tabs. A recent rename migration swapped two labels: "Settings" now contains the members table, while "Members" shows billing receipts.',
      navKind: 'tabs',
      tabs: [
        { label: 'Overview', isActive: true },
        { label: 'Members', misleading: true },
        { label: 'Settings', misleading: true },
        { label: 'Integrations' },
      ],
    },
  },
  {
    id: 'back-button',
    title: 'Back Button Wizard',
    tagline: 'Pressing back silently throws away your draft.',
    goal: 'Edit the shipping address on step 2 of the checkout wizard.',
    rules: [
      'Keep the cart contents intact',
      'Do not lose the payment info already entered on step 3',
    ],
    traps: [
      'Browser back deletes the in-progress order draft',
      'The "Edit shipping" link on the right rail is the safe way back',
    ],
    difficulty: 'medium',
    estimatedSeconds: 40,
    category: 'navigation',
    template: 'navigation-puzzle',
    actionSpec: {
      prompt: 'Go back to step 2 to fix the shipping address without losing what you typed on step 3.',
      correct: {
        id: 'click-edit-shipping',
        label: 'Click "Edit shipping address" in the summary rail',
        successMessage: 'Returned to step 2 with the draft preserved.',
      },
      others: [
        {
          id: 'click-browser-back',
          label: 'Press the browser Back button',
          description: 'Native back navigation',
          kind: 'danger',
        },
        {
          id: 'click-restart-wizard',
          label: 'Click "Start over"',
          description: 'Restart the checkout flow',
          kind: 'danger',
        },
        {
          id: 'click-step-1',
          label: 'Click the "Cart" step in the breadcrumb',
          description: 'Jumps back to step 1',
          kind: 'wrong',
        },
      ],
    },
    templateData: {
      productName: 'Patagonia Checkout',
      headline: 'Checkout — Step 3 of 4: Payment',
      body: 'You are on step 3. Step 2 needs a fix. The wizard uses an SPA history stack that drops draft state on browser back; only the right-rail "Edit shipping" link preserves the draft.',
      navKind: 'back-button',
      breadcrumb: ['Cart', 'Shipping', 'Payment', 'Review'],
    },
  },
  {
    id: 'nested-menu',
    title: 'Nested Menu',
    tagline: 'Three levels of hover menus, one finicky path.',
    goal: 'Open the Security settings.',
    rules: [
      'Use the top-bar account menu',
      'Do not sign out',
    ],
    traps: [
      'Hover lag closes the submenu if you cut the corner',
      'Two different "Security" labels exist — one is under Privacy, the other under Account',
    ],
    difficulty: 'medium',
    estimatedSeconds: 45,
    category: 'navigation',
    template: 'navigation-puzzle',
    actionSpec: {
      prompt: 'Pick the menu item that opens the Security settings.',
      correct: {
        id: 'click-account-security',
        label: 'Security (Account)',
        successMessage: 'Security pane open.',
      },
      others: [
        {
          id: 'click-privacy-security',
          label: 'Security (Privacy)',
          description: 'Different Security submenu under Privacy',
          kind: 'wrong',
        },
        {
          id: 'click-account-profile',
          label: 'Profile',
          description: 'Sibling item in the same submenu',
          kind: 'wrong',
        },
        {
          id: 'click-sign-out',
          label: 'Sign out',
          description: 'Last item in the account menu',
          kind: 'danger',
        },
      ],
    },
    templateData: {
      productName: 'Google-style Account Menu',
      headline: 'Account dropdown',
      body: 'A three-deep hover menu hangs from your avatar. Settings expands into six categories; Account expands further into Profile, Security, Sessions, and Devices.',
      navKind: 'nested-menu',
      menuTree: [
        {
          label: 'Settings',
          children: [
            { label: 'Account' },
            { label: 'Privacy' },
            { label: 'Appearance' },
            { label: 'Notifications' },
          ],
        },
        { label: 'Help' },
        { label: 'Sign out' },
      ],
    },
  },
  {
    id: 'mega-menu',
    title: 'Mega Menu',
    tagline: 'Twelve columns of links. Integrations is in column 9.',
    goal: 'Open the Integrations marketplace from the marketing site nav.',
    rules: [
      'Use the global mega-menu, not the footer',
      'Do not click any sales-contact CTA',
    ],
    traps: [
      'Two columns reuse the word "Connect"',
      'A promoted "Featured: Slack" tile in column 2 routes to a partner landing page',
    ],
    difficulty: 'medium',
    estimatedSeconds: 40,
    category: 'navigation',
    template: 'navigation-puzzle',
    actionSpec: {
      prompt: 'Find Integrations in the mega-menu and open it.',
      correct: {
        id: 'click-column9-integrations',
        label: 'Click "Integrations" in column 9 ("Developers")',
        successMessage: 'Integrations marketplace open.',
      },
      others: [
        {
          id: 'click-featured-slack',
          label: 'Click the "Featured: Slack" tile',
          description: 'Promoted tile in column 2',
          kind: 'wrong',
        },
        {
          id: 'click-column3-connect',
          label: 'Click "Connect" in column 3 ("Solutions")',
          description: 'Same-named entry under Solutions',
          kind: 'wrong',
        },
        {
          id: 'click-talk-to-sales',
          label: 'Click "Talk to sales" in the right rail',
          description: 'CTA on the right edge of the mega-menu',
          kind: 'wrong',
        },
      ],
    },
    templateData: {
      productName: 'Salesforce.com Marketing Site',
      headline: 'Products mega-menu',
      body: 'The Products mega-menu sprawls across twelve columns: Platform, Sales, Service, Marketing, Commerce, Analytics, Industries, Solutions, Developers, Partners, Customers, Resources. Integrations lives under Developers.',
      navKind: 'mega-menu',
      menuTree: [
        { label: 'Platform' },
        { label: 'Sales' },
        { label: 'Service' },
        { label: 'Marketing' },
        { label: 'Commerce' },
        { label: 'Analytics' },
        { label: 'Industries' },
        { label: 'Solutions' },
        {
          label: 'Developers',
          children: [
            { label: 'Docs' },
            { label: 'API Reference' },
            { label: 'Integrations' },
            { label: 'SDKs' },
          ],
        },
        { label: 'Partners' },
        { label: 'Customers' },
        { label: 'Resources' },
      ],
    },
  },
  {
    id: 'search-redirect',
    title: 'Search Redirect',
    tagline: 'The first three results are paid ads.',
    goal: 'Open the official React documentation site.',
    rules: [
      'Use the search results page that is already loaded',
      'Do not click sponsored results',
    ],
    traps: [
      'Results #1–#3 are ad placements that look like organic links',
      'The real react.dev result is #4',
    ],
    difficulty: 'medium',
    estimatedSeconds: 35,
    category: 'navigation',
    template: 'navigation-puzzle',
    actionSpec: {
      prompt: 'Open the React docs.',
      correct: {
        id: 'click-result-4',
        label: 'Open result #4: react.dev — official docs',
        successMessage: 'Opened the real React docs.',
      },
      others: [
        {
          id: 'click-result-1',
          label: 'Open result #1: "React Course – 90% off today"',
          description: 'Top result, marked Sponsored in small grey text',
          kind: 'wrong',
        },
        {
          id: 'click-result-2',
          label: 'Open result #2: "Hire React Developers — Fiverr"',
          description: 'Second sponsored result',
          kind: 'wrong',
        },
        {
          id: 'click-result-3',
          label: 'Open result #3: "React tutorial PDF – free download"',
          description: 'Third sponsored result',
          kind: 'wrong',
        },
      ],
    },
    templateData: {
      productName: 'Google Search Results',
      headline: 'Results for "react documentation"',
      body: 'A Google-style results page. The top three entries carry a tiny "Sponsored" pill above the title; the fourth is the first organic result.',
      navKind: 'search',
      searchResults: [
        { title: 'React Course – 90% off today', url: 'https://learnreact.promo', promoted: true },
        { title: 'Hire React Developers — Fiverr', url: 'https://fiverr.com/react', promoted: true },
        { title: 'React tutorial PDF – free download', url: 'https://reactpdf.download', promoted: true },
        { title: 'React – The library for web and native user interfaces', url: 'https://react.dev' },
        { title: 'React (software) – Wikipedia', url: 'https://en.wikipedia.org/wiki/React_(software)' },
      ],
    },
  },
  {
    id: 'language-switch',
    title: 'Language Switch',
    tagline: 'The page loaded in Japanese. Switch to English first.',
    goal: 'Switch the site language to English before reading the article.',
    rules: [
      'Use the language switcher in the header',
      'Do not use the browser translate feature',
    ],
    traps: [
      'The language menu is iconographic (a globe)',
      'A "EN" badge in the footer is a country flag for Estonia',
    ],
    difficulty: 'medium',
    estimatedSeconds: 35,
    category: 'navigation',
    template: 'navigation-puzzle',
    actionSpec: {
      prompt: 'Set the site language to English.',
      correct: {
        id: 'pick-english',
        label: 'Open the globe menu and pick "English"',
        successMessage: 'Locale switched to en-US.',
      },
      others: [
        {
          id: 'pick-estonia-flag',
          label: 'Click the "EN" badge in the footer',
          description: 'Footer icon that looks like an English toggle',
          kind: 'wrong',
        },
        {
          id: 'pick-german',
          label: 'Open the globe menu and pick "Deutsch"',
          description: 'Top-level Germany option',
          kind: 'wrong',
        },
        {
          id: 'use-browser-translate',
          label: 'Right-click and use "Translate page"',
          description: 'Browser-level translation',
          kind: 'wrong',
        },
      ],
    },
    templateData: {
      productName: 'Wikipedia',
      headline: 'パリ — ウィキペディア',
      body: 'The article loaded in Japanese because of an Accept-Language header mismatch. A globe icon in the header opens a list of locales; the footer also has an "EN" badge that is actually the Estonian flag.',
      navKind: 'language',
      languages: ['日本語', 'English', 'Deutsch', 'Français', 'Eesti', '한국어', '中文'],
    },
  },
  {
    id: 'pagination-trap',
    title: 'Pagination Trap',
    tagline: 'Twelve pages of orders. The one you want is on page 4.',
    goal: 'Open order #ORD-1042, which is on page 4 of the orders table.',
    rules: [
      'Use the table pagination controls',
      'Do not change the rows-per-page setting',
    ],
    traps: [
      'The "Next" button skips two pages on the first click',
      'A "Jump to last" shortcut is prominent and tempting',
    ],
    difficulty: 'medium',
    estimatedSeconds: 40,
    category: 'navigation',
    template: 'navigation-puzzle',
    actionSpec: {
      prompt: 'Navigate to page 4 of the orders table.',
      correct: {
        id: 'click-page-4',
        label: 'Click the "4" page-number button',
        successMessage: 'On page 4; ORD-1042 visible.',
      },
      others: [
        {
          id: 'click-next',
          label: 'Click "Next" repeatedly',
          description: 'Pager next-arrow (broken: skips two)',
          kind: 'wrong',
        },
        {
          id: 'click-last',
          label: 'Click "Jump to last"',
          description: 'Shortcut to page 12',
          kind: 'wrong',
        },
        {
          id: 'change-rows-per-page',
          label: 'Change "Rows per page" to 100',
          description: 'Re-paginates the entire table',
          kind: 'wrong',
        },
      ],
    },
    templateData: {
      productName: 'Shopify Admin — Orders',
      headline: 'Orders (847 total)',
      body: 'A data table with 12 pages of orders at the default 75 rows per page. Order ORD-1042 falls on page 4. The "Next" arrow has a bug that double-advances on first click.',
      navKind: 'pagination',
      pages: 12,
    },
  },
  {
    id: 'canonical-url',
    title: 'Canonical URL',
    tagline: 'You arrived via a tracking link. The real URL is in <head>.',
    goal: 'Open the canonical link declared in the page head.',
    rules: [
      'Use the canonical URL exposed by the page',
      'Strip tracking parameters before sharing',
    ],
    traps: [
      'The address bar shows a UTM-laden URL',
      'A "Share this page" button copies the tracking URL, not the canonical one',
    ],
    difficulty: 'medium',
    estimatedSeconds: 40,
    category: 'navigation',
    template: 'navigation-puzzle',
    actionSpec: {
      prompt: 'Open the canonical version of this article.',
      correct: {
        id: 'open-canonical',
        label: 'Open the URL from <link rel="canonical">',
        successMessage: 'Opened the canonical article URL.',
      },
      others: [
        {
          id: 'copy-share-button',
          label: 'Click "Share this page"',
          description: 'Copies the current URL with all UTM tags',
          kind: 'wrong',
        },
        {
          id: 'reload-current',
          label: 'Reload the current tracking URL',
          description: 'Stay on the UTM URL',
          kind: 'wrong',
        },
        {
          id: 'open-amp-version',
          label: 'Open the "View AMP version" link',
          description: 'Alternative mobile-AMP URL',
          kind: 'wrong',
        },
      ],
    },
    templateData: {
      productName: 'The New York Times',
      headline: 'How the city redrew its bike lanes',
      body: 'The article URL in the address bar is https://nyti.ms/abc?utm_source=twitter&utm_campaign=launch&ref=share. The page head declares <link rel="canonical" href="https://www.nytimes.com/2026/05/12/nyregion/bike-lanes.html">.',
      navKind: 'canonical',
      searchResults: [
        { title: 'Current tab (tracking URL)', url: 'https://nyti.ms/abc?utm_source=twitter&utm_campaign=launch&ref=share' },
        { title: 'Canonical link (in <head>)', url: 'https://www.nytimes.com/2026/05/12/nyregion/bike-lanes.html' },
      ],
    },
  },
];

export default familyNavigation;
